### ISSUE TITLE
question/feature: Helmsman way to rollback failed releases

### ISSUE THREAD

**Issue by hasueki** [Praqma/helmsman#198]
What is the recommended way to rollback `FAILED` chart releases?

I was hoping that Helmsman would have a rollback feature that will automatically rollback the chart to the previous release for a failed upgrade. 

Or, will it be better to handle it in our pipeline to either revert the breaking commit to the DSF or make a new commit to upgrade the failed chart to the previous version?

**Comment by sami-alajrami** [comment]
helmsman's behaviour is to upgrade a failed release when it finds one. This means you can either revert the breaking commit to the previous desired state (rollback) or push a new commit with a fix (upgrade). Either way, helmsman will do an upgrade to the failed release (with previous config or new fixed config).

The reason why helmsman doesn't rollback a failed release automatically is that some helm releases have had a rollback bug which meant rollbacks won't work. I believe this has been fixed in helm at some point but the helmsman behaviour persisted.

**Comment by hasueki** [comment]
@sami-alajrami
Thanks for the reply, so an issue with helm was blocking this auto rollback feature.
I was thinking of having a flag in the DSF to either enable/disable auto-rollback for a certain chart.
Do you think such functionality will be useful now that helm rollback has matured since then?

**Comment by hasueki** [comment]
The only thing that may be an issue here is that if auto rollback is performed, there will a discrepancy between the DSF and what is installed on the cluster.

**Comment by sami-alajrami** [comment]
True about the discrepancy. IMHO I prefer that the use either: 
1. revert the commit to trigger a rollback (through upgrade to older config). This of course requires smaller changes/commits which is a good practice.  
2. make a new commit fixing the breaking change and triggering a normal upgrade.

This way the DSF will always reflect what's in the cluster and users will be following a [GitOps](https://www.weave.works/technologies/gitops/) style where you manage infra and deployments with git commits.

**Comment by hasueki** [comment]
Yeah I agree with you there. Ok thanks for the info!
