### ISSUE TITLE
Ability to add hooks and scripts?

### ISSUE THREAD

**Issue by musabmasood** [Praqma/helmsman#303]
Is there a plan (or way) to add hooks/scripts during the lifecycle? For instance, after all charts have been upgraded, I want to run a script that runs some curls against the deployed services or initialize some databases etc.

**Comment by sami-alajrami** [comment]
@musabmasood sorry for the late response .. for the use cases you mentioned, you could use [helm hooks](https://helm.sh/docs/topics/charts_hooks/) in your chart to run a post-install/post-upgrade jobs which basically run your scripts. Alternatively, if you want to perform some tests on the apps you could use [helm tests](https://helm.sh/docs/topics/chart_tests/) and configure `test = true` for your releases so that Helmsman triggers the tests after install. 

If this is on 3rd party charts, I recommend having your additional custom setup in a new chart and specify it's order in the DSF to run right after the 3rd party chart. 

Ability to run custom kubectl operations before/after helm operations might be added in Helmsman 3.x but might not support scripts. My main concern about arbitrary scripts is that it is harder to rollback or remove their effect when performing rollbacks or deletion from helm. Thus potentially compromizing idempotency in Helmsman's operations. Additionally scripts will depend on the environment where Helmsman is running and that can bring up incompatibility issues. So I recommend having scripts to run in containers as pods/jobs in k8s and managed by your helm charts.

**Comment by kferrone** [comment]
This also would be related to #414 and #360
