### ISSUE TITLE
Helmsman CRD's in --dry-run mode

### ISSUE THREAD

**Issue by debek** [Praqma/helmsman#377]
Hi,

I have run my helmsman with this flags "--dry-run --show-diff --suppress-diff-secrets --keep-untracked-releases" to check if prometheus-operator will be installed correctly.
After that and check I got a message"
"WARNING: Validation skipped because CRDs are not installed"
Seems like helmsman in dry-run mode don't install CRD's. Have you got work around for it?

**Comment by luisdavim** [comment]
that's probably because those CRDs are installed with a hook a dry run won't trigger the hooks and it shouldn't or it wouldn't be a dry run.
you can install those CRDs yourself manuall, helm isn't great managing CRDs anyway, what I normally do it having the CRDs in a separate helm chart that I install first but I think helm v3 has some solution for that, I haven't investigated that yet.

**Comment by mkubaczyk** [comment]
I've got the same opinion on how to manage CRDs with Helmsman as @luisdavim. We're usually having helm chart named crds and we're always installing it before anything else and I'm not letting other charts install their CRDs on their own. Not as clean as it should be, but pays the bills for now.

**Comment by debek** [comment]
It helped. Thanks guys!
