### ISSUE TITLE
Output some notes like Helm does for charts

### ISSUE THREAD

**Issue by schollii** [Praqma/helmsman#39]
When you run helm install, it outputs the contents of Notes.txt for the chart. This is handy to explain how to test the chart. Similarly, there should be a way to specify notes when helmsman --apply is run. Outputting the individual chart notes may not be very useful, because the notes you would want would be for the "group" of charts deployed. For example, a good place to add notes about testing that the deployed services are reachable. 

So I imagine a Notes file specific to each namespace (since if I am not mistaken, all apps items in the TOML file that match a certain namespace get installed) in the same folder as the toml. It could similarly be parameterized so that the output contains actual values taken from the various values files and toml.

**Comment by sami-alajrami** [comment]
thanks @schollii .. First, to clarify, apps could be installed in different namespaces (depending on the namespace you define for each app) .. not only in one specific namespace. 

I see your point about Notes, but wouldn't that be reinventing the wheel from Helm? .. 
Printing alI Notes isn't useful as you mentioned because it will be a lot of text for multiple apps ..  I was thinking of something like a diff of before and after the change maybe ? 
Is that something you would find useful?

**Comment by schollii** [comment]
Maybe just add a command like "helmsman get-notes" to output all Notes.txt. Allow conditions like enabled=true, namespace=something, etc. E.g. "helmsman get-notes  --namespace=something --enabled=false". Output format: maybe support a couple of formats like raw text, md, json, yaml, all that does is determine the "skeleton" that notes get put into (like for raw text, just separate the notes by "--- chart name" lines; for json, something like 
notes:
```
    - chart: 
       text: |-
           ...
```
)

This might be quite easy to implement and gives user a lot of freedom (save the output, further process the output, just dump to standout, choose which ones they want, etc).

**Comment by luisdavim** [comment]
regarding the diff idea, what do you think about #74 ?
