### ISSUE TITLE
How to construct deployments file for multi apps without failing.

### ISSUE THREAD

**Issue by mhobotpplnet** [Praqma/helmsman#440]
So we are deploying apps with helmsman which reads charts from chartmuseum. 

Most of our apps are constructed as 

app1:
appinfo:
apprepo: etc etc

app2:
appinfo: 

So that said, if say in our CD, app 1 fails because of values file is not good, app 2 never gets deployed so we have to make sure that all apps are green before it can be pushed to an environment..

Any ideas around this?

**Comment by sami-alajrami** [comment]
There are a couple of options:
- split your apps into multiple helmsman files if possible to make it easier for you to manage. This means you would deploy different (groups of) apps separately. To avoid duplication of config, you can have a global file with common config (e.g. helm repos, context etc) and merge it with each app-specific file (`helmsman apply -f common.yaml -f specific.yaml)` 

- You can use the `--target` or `--group` flags to limit execution to a specific application. See [this](https://github.com/Praqma/helmsman/blob/master/docs/how_to/misc/limit-deployment-to-specific-apps.md) guide and [this](https://github.com/Praqma/helmsman/blob/master/docs/how_to/misc/limit-deployment-to-specific-group-of-apps.md) one.  

- You can also use [priorities](https://github.com/Praqma/helmsman/blob/master/docs/how_to/apps/order.md) to define which apps are operated on first.
- If the failures are caused by validation (e.g. wrong chart version) and you want to skip it, you can use the `--skip-validation` flag.
