### ISSUE TITLE
Devel versions of packages doesn't work with helmsman 3.3.0

### ISSUE THREAD

**Issue by ezlo-eugenek** [Praqma/helmsman#456]
I have helm charts with devel versions like 0.1.0-d-42gsd23

All was working fine with helmsman 3.1.0, but when I tried to upgrade to 3.3.0 faced with issue that helm chart cannot be found. With debug log I can see that new additional command was added in 3.3.0 which is not present in 3.1.0, it is helm show command:

`Step #2 - "Helmsman apply": [37m2020-05-09 15:55:42 INFO: Show chart information[0m
Step #2 - "Helmsman apply": [36m2020-05-09 15:55:42 DEBUG: helm show chart test-helm-repo/test-test-server[0m

Step #2 - "Helmsman apply": [35m2020-05-09 15:55:43 CRITICAL: While getting chart information: Error: failed to download "test-helm-repo/test-test-server" (hint: running `helm repo update` may help)
Step #2 - "Helmsman apply": [0m`

When I am trying to run same command:
`helm show chart test-helm-repo/test-test-server`
I also get this this error - failed to download...
But it returns package with --devel flag, but not last one, not clear why.

I tried to use helmsman 3.1.0 and helm 3.2.1 - it is working fine, so reason is in not in helm. 

helmsman is launched with flags:
helmsman -apply -f development.toml -debug -verbose -show-diff

I don't know for what 'helm show chart' was added, maybe it is possible to disable it in 3.3.0 ?
Any idea ?

**Comment by sami-alajrami** [comment]
the `show` command was introduced [here](https://github.com/Praqma/helmsman/commit/7e139900f22acdf57e666231733b29c7b8831c16#diff-d3a54a19ed6311b4ceebe7b5d12028b7). It makes the extraction of chart info more reliable since it uses the chart information returned from helm show. The previous code simply processed the string from the desired state file. 

If I create a test chart and use the same version you have and use `helm show chart test` the command works fine for me. 
Is this a private repo (with username and password)?
Also the [Semver spec](https://semver.org/#spec-item-9) states the following about pre-release versions:  `A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version.` and you have two hyphens. It's worth trying to replace the second one with a dot.

**Comment by boxcee** [comment]
Having the same problem here.

We have a chart which only has development versions. E.g. `0.1.1-development`, `0.1.2-developmen`. **NO** `0.1.1` or `0.1.2` versions!

They are uploaded to a private repository. I can verify `helm show chart mychart` doesn't show any results, but `helm show charts mychart --devel` shows me the latest versioned development chart `0.1.2-development`.

**Comment by boxcee** [comment]
Actually there should be an easy fix. `helm show chart` has a flag `--version` when set, it will include development versions. I think that should be added to the command.

**Comment by boxcee** [comment]
Wow, that was quick! Awesome!

**Comment by pmjacinto** [comment]
@sami-alajrami it seems this change got "lost" with 3.4.2 (it only made it to 3.4.1, and it's no longer in master).

https://github.com/Praqma/helmsman/commits/master/internal/app/helm_helpers.go

**Comment by sharkymcdongles** [comment]
@sami-alajrami +1 to the above. We would like to use the latest, but this devel issue is a problem for us.
