### ISSUE TITLE
Helmsman skipping deploys where same chart version is already deployed

### ISSUE THREAD

**Issue by kbirger** [Praqma/helmsman#487]
> DECISION: release [ my-app ] is desired to be enabled and is currently enabled. Nothing to do here! -- priority: 0

That is the message I get. I am not sure if there is a way to get this to work with existing settings, or if it would require a feature update.

There are cases where we want to redeploy the same version of a chart because:

1. We had to manipulate the chart's k8s resources directly on the cluster for troubleshooting and want to roll back the manual changes (my actual scenario)
2. We want to re-deploy the same chart with different settings (have not actually tested this yet, but suspect it would behave the same as I **did** test by DELETING everything in k8s but leaving the chart released).

It is not desirable to have a check under these circumstances which simply short circuits the deploy because the versions match up.

So is there a way to configure this with the existing version?

Using the latest Helmsman and latest Helm v2 version (We are not on v3 yet)

**Comment by mkubaczyk** [comment]
helm-diff is deciding on it based on the differences between current state on the cluster and the desired state from interpolated templates from your chart. If there's no change, it won't do anything, so that is expected. You can redeploy it by disabling it and then enabling again or by passing some value that is different comparing to the one from previous deployment, so the diff will discover that change.

**Comment by kbirger** [comment]
Sure, I could do all of those things and more, but isn't the purpose of this tool to be able to declaratively set an environment into a state which is declaratively defined? 

If I have to manually manipulate settings on my state just to get it to do what I want, it sort of defeats the purpose. I believe that is the reason that Helm provides a --force flag, so that you can make your operation idempotent regardless of the current state of things. In fact, I see that this flag is supported by Helmsman. Unfortunately in my case, Helm is not even being executed since Helmsman is optimistically assuming that the state is correct.

My goal is to have this run unattended, so I can't be marking settings just to fool helm-diff into seeing the truth: that my environment is **not** in the state that was last recorded.

**Comment by mkubaczyk** [comment]
It's a matter of how Helm is able to discover changes you did manually rather Helmsman itself. I'd say it's undesired to manually mess with anything that is being managed by Helm, at least with current state of Helm where it has hard times discovering such changes happening.

**Comment by kbirger** [comment]
Yes, I understand the conundrum, but is it not also interfering with Helm by preempting it in this instance? I'm not saying that the existing behavior is undesired in every case, but do you not think it's a valid usecase for Helmsman to use it on a non-prod environment that may have manual changes due to the need to troubleshoot?

All I am proposing is a flag that allows the user to disable the heuristic functionality that improves execution time by optimizing away Helm calls that it thinks are unnecessary

**Comment by luisdavim** [comment]
The main idea behind Helmsman and helm is that you don't make manual changes and you keep track of the deployed configurations in git.

You are welcome to open a pr to add a flag to ignore the actual state and force the deployment

**Comment by bergerx** [comment]
This issue keeps hitting us again and again.

This behaviour from helm-diff plugin actually brings back the old 3-way-merge vs 2-way-merge problematic which helm 2 used to have, and helm project eventually forced to solve it helm3, see https://github.com/helm/helm/issues/3805 for more details and related issues there.

So helmsman is not aligned with helm's behaviour after updates in Helm 3.

Here is an example with helm:
* i deployed `bitnami/postgresql-ha` using `helm`
* some operator manually deleted the `StatefulSet` by mistake
* i re-ran last `helm upgrade`, problem solved

Same helmsman:
* i deployed `bitnami/postgresql-ha` using `helmsman`
* some operator manually deleted the `StatefulSet` by mistake
* i re-ran `helmsman`, it didnt fix anything
* (there is no way to fix the situation without manually running the helm command that helmsman runs)

**The real issue here calculating diff against "last known to be helm deployed" rather than "what currently is running".** I expect not the first, people usually don't care about the first one, they do care about the second. I can't think of any valid case to factor in the first explicitly ignoring potential problems with the second. But checking helm-diff it explicitly does the first one, which is usually not the intention:
> This is a Helm plugin giving your a preview of what a helm upgrade would change. It basically generates a diff between the latest deployed version of a release and a helm upgrade --debug --dry-run. This can also be used to compare two revisions/versions of your helm release.

Now that helm fixed this problem in helm 3, i think same needs to be addressed in helmman. If the helm-diff plugin owner is fine to address this, no change may be required in helmsman but if they refuse, i think we need to think something else

**Comment by bergerx** [comment]
I commented on the https://github.com/databus23/helm-diff/issues/176 issue, and apparently helmfile is also hit with the same issue and they now consider switching rather to kubectl diff: https://github.com/roboll/helmfile/issues/1376

**Comment by luisdavim** [comment]
Can we consider this fixed now that we have the `--always-upgrade` flag?

**Comment by bergerx** [comment]
We are using the release revision as a signal to identify if any changes are applied recently and to see what was changed.

Using --always-upgrade flag prevents that, we not just lose the signal and after running helmsman couple of times without a change we'll even lose the ability to see the change anymore due to the`--history-max` in helm.

We can't just keep revision histories forever, its not just polluting the namespace with secrets, the revision secrets are used to be quite big, as they are accumulating even a simple `helm ls` may need to download couple hundred megabytes of data.

**Comment by luisdavim** [comment]
Are you always using the same chart version? Why are you trying to redeploy the same version? Did you do any manual changes outside of helm to the k8s resources?

**Comment by bergerx** [comment]
> Are you always using the same chart version?
Not always but quite regularly. If the change is a change in values file, yes. We also regularly kick them off to reduce possible configuration drifts.

> Why are you trying to redeploy the same version?
We have a couple dozen helm releases in a single merged DSF. When there is a change on any of them we trigger helmsman. We also have various number of cases that helmsman is triggered unnecessarily. But this exact feature is also why we wanted to use Helmsman, it checks changes first and try not to apply if there is no change. Helmsman actually depends on helm-diff for that, which not yet supports 3 way merge and its been hurting us in multiple ways.

> Did you do any manual changes outside of helm to the k8s resources?
One can't easily guarantee there wont be any changes introduced outside of helm. Its safer to assume there could be changes and depend on Helm(sman) to revert.

**Comment by bergerx** [comment]
If https://github.com/helm/helm/issues/9220#issuecomment-826666672 is implemented, maybe we can skip calling helm-diff when a certain flag is set and instead start depending on pure helm. helm-diff dependency has been hitting us in various ways for a long while.

Actually if this is implemented in helm, i believe there wont be any reason to avoid running a `helm upgrade` every time we issue a helmsman apply.

**Comment by luisdavim** [comment]
> If [helm/helm#9220 (comment)](https://github.com/helm/helm/issues/9220#issuecomment-826666672) is implemented, maybe we can skip calling helm-diff when a certain flag is set and instead start depending on pure helm. helm-diff dependency has been hitting us in various ways for a long while.
> 
> Actually if this is implemented in helm, i believe there wont be any reason to avoid running a `helm upgrade` every time we issue a helmsman apply.

Yeah, that's what `-always-upgrade` does, it skips the `helm diff` command and runs `helm upgrade` the main issue being reported here is really a `helm-diff` issue (https://github.com/databus23/helm-diff/issues/176)

**Comment by luisdavim** [comment]
I can try making some experiments with something like `kubectl diff -f <(helm template ...)` and see if that could replace `helm-diff`

**Comment by luisdavim** [comment]
This is still WIP as I haven't had a chance to test it yet but https://github.com/Praqma/helmsman/pull/609 should allow using `kubectl diff` instead of the `helm diff` plugin and solve this problem.
If you have a chance please do test it and let me know how it goes @bergerx .
