### ISSUE TITLE
Changing chart results in invalid `helm uninstall` command

### ISSUE THREAD

**Issue by sarumont** [Praqma/helmsman#502]
Helmsman `3.4.2`

I am updating a helm release in our Helmsman-managed environment to pull a new chart. Helmsman detects the change properly, but when it issues the `uninstall` command, it is missing the namespace:

```
2020-07-08 02:47:28 NOTICE: -------- PLAN starts here --------------
...
2020-07-08 02:47:28 NOTICE: Release [ gateway ] is desired to use a new chart [ neverfail/dana ]. Delete of the current release will be planned and new chart will be installed in namespace [ default ] -- priority: 0
...
2020-07-08 02:47:28 NOTICE: -------- PLAN ends here --------------
2020-07-08 02:47:28 INFO: Printing the commands of the current plan ...
helm uninstall --namespace  gateway
helm upgrade gateway neverfail/dana --install --version 0.2.2 --namespace default --set fullnameOverride=gateway --set global.vault.name=nf-centralus-***-default --set global.vault.prefix=*** --set devMode=false --set image.tag=1.2.1 --set schema.image.tag=1.0.0 
2020-07-08 02:47:28 INFO: Executing plan... 
2020-07-08 02:47:28 NOTICE: Delete release [ gateway ] in namespace [  ]
2020-07-08 02:47:28 DEBUG: helm uninstall --namespace  gateway
2020-07-08 02:47:28 CRITICAL: Command for release [gateway] returned [ 1 ] exit code and error message [ Error: "helm uninstall" requires at least 1 argument
```

Note: `helm uninstall --namespace  gateway` doesn't have the `default` namespace specified, so `--namespace` eats the name of the deployment, leaving `helm` one argument short. :)

**Comment by bergerx** [comment]
Please also consider #538 when working on this.

**Comment by erpel** [comment]
I'm also seeing this on v3.4.6 even with a namespace defined in the desired state.
The --namespace flag is immediately followed by the release name.

**Comment by bergerx** [comment]
Ah just realised this is exactly same issue with https://github.com/Praqma/helmsman/issues/538. Please review that one and dont just fix the uninstall. Now that helm supports upgrading an existing release with a different chart, Helmsman doesn't need to (and should not) uninstall the old release at all.

**Comment by erpel** [comment]
If one were to add special handling for this case, it might be a good idea to supply/set "--set nameOverride=" automatically, though I do not know enough about all the use cases to know if this is actually appropriate as default behaviour.

**Comment by luisdavim** [comment]
It's not guaranteed that all helm charts support overriding  the release name with the `nameOverride` or `fullNameOverride` values, I think we'd need some flag to indicate if you want that release to be upgraded or replaced and then if the user chooses to upgrade it would be up to the user to set the values accordingly....

Any suggestions?

BTW: I think the bug is that https://github.com/Praqma/helmsman/blob/master/internal/app/decision_maker.go#L404 instead of  `r.reInstall(p)` it should be something like:
```go
rs.uninstall(p)
r.install(p)
```

**Comment by bergerx** [comment]
I'd expect the default behaviour to be aligned with helm's default
behaviour. So it should be in-place upgrade with the new chart, this is the
default helm behaviour since Helm 3 i guess.

So if anyone ever needs, we can have a flag to support explicit reinstall
(uninstall/install), but given that this bug has been here for a long
while now, i suspect anyone needs or uses this feature. So maybe not needed
at all.

**Comment by luisdavim** [comment]
Does it work if the chart doesn't support the name override? How does it behave if you don't set it?

**Comment by bergerx** [comment]
No special logic, just based on the templates used in the chart, it will
likely replace the resources which has names depend on the chart name with
new ones.

So assuming most resources will use the default template provided by helm
create (
https://github.com/helm/helm/blob/8667aa4f98574008947ee39c2e583e359fd687c1/pkg/chartutil/create.go#L414)
its almost always the case that all resources will be replaced with new one
that has new names. As mentioned above the only workaround is providing a n
explicit nameOverride/fullNameOverride during upgrade if the chart supports
those values.

This is what Helm does as i know.

**Comment by luisdavim** [comment]
ok, I have a rather large PR open right now, I'll work on this once that's merged.

**Comment by luisdavim** [comment]
I've opened https://github.com/Praqma/helmsman/pull/546, can you guys give it a test using your use cases?
