### ISSUE TITLE
Azure Container Registries now supports Helm repos

### ISSUE THREAD

**Issue by patrickmslatteryvt** [Praqma/helmsman#99]
Azure Container Registries (ACR) now supports Helm repos:
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-helm-repos

However the ACR Helm repos are private and therefore do not work with the current version of Helmsman, example below:

```
helmsman -dry-run -f ./src/helmsman.infra.toml
 _          _ 
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v1.6.1
A Helm-Charts-as-Code tool.

2018/10/03 23:00:37 INFO: Parsed TOML [[ ./src/helmsman.infra.toml ]] successfully and found [ 11 ] apps.
2018/10/03 23:00:37 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ weave-scope ].
2018/10/03 23:00:37 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ tls ].
2018/10/03 23:00:37 INFO: namespace validation -- Tiller is NOT desired to be deployed in namespace [ infra ].
2018/10/03 23:00:38 WARN: I could not create namespace [weave-scope ]. It already exists. I am skipping this.
2018/10/03 23:00:38 WARN: I could not create namespace [tls ]. It already exists. I am skipping this.
2018/10/03 23:00:39 WARN: I could not create namespace [infra ]. It already exists. I am skipping this.
2018/10/03 23:00:39 INFO: deploying Tiller in namespace [ kube-system ].
2018/10/03 23:00:40 INFO: posting notifications to slack ... 
2018/10/03 23:00:40 ERROR: while adding repo [###containers]: Error: Looks like "https://###containers.azurecr.io/helm/v1/repo" is not a valid chart repository or cannot be reached: Failed to fetch https://###containers.azurecr.io/helm/v1/repo/index.yaml : 401 Unauthorized

curl --silent https://###containers.azurecr.io/helm/v1/repo/index.yaml | jq .
{
  "errors": [
    {
      "code": "UNAUTHORIZED",
      "message": "authentication required",
      "detail": [
        {
          "Type": "artifact-repository",
          "Name": "repo",
          "Action": "pull"
        }
      ]
    }
  ]
}
```

Are there any plans to support this repo type?

**Comment by luisdavim** [comment]
There is support for private repos but I think it's specific to S3 and GCS:
https://github.com/Praqma/helmsman/blob/master/docs/how_to/use_private_helm_charts.md

**Comment by sami-alajrami** [comment]
@patrickmslatteryvt we have been using helm plugins to support private repos in [S3](https://github.com/hypnoglow/helm-s3) and [GCS](https://github.com/nouney/helm-gcs) .. after a quick check, I could not find any existing helm plugins to handle azure private charts. We will support this once such a plugin exists.

**Comment by mmisztal1980** [comment]
July 2020: Any updates on this? is it possible to use Helmsman with ACR yet?

**Comment by bergerx** [comment]
I think this issue should be addressed as a generic HELM_EXPERIMENTAL_OCI support.
This process is actually vaguely defined in https://helm.sh/docs/topics/registries/ and can be used for any OCI compliant container registries and not really specific to ACR.

Here is what is expected to install a helm chart hosted on ACR:
```
export HELM_EXPERIMENTAL_OCI=1
echo $spPassword | helm registry login mycontainerregistry.azurecr.io --username <service-principal-id> --password-stdin
helm chart pull mycontainerregistry.azurecr.io/helm/hello-world:v1
helm chart export mycontainerregistry.azurecr.io/helm/hello-world:v1 --destination ./install
cd install
helm install myhelmtest ./hello-world
```

Here is a very similar document for using ECR as a helm repo: https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html

The the underlying issue here is the way HELM_EXPERIMENTAL_OCI support works. It doesn't work as a regular `helm repo` but expects users to `helm chart pull + helm chart export + helm install` rather than conventional `helm repo add + helm install` sequence. I'm not sure if this can be handled by a helm plugin (maybe it can, i just don't know). Also there seem to be lots of discussions around this on the helm project (https://github.com/helm/community/pull/136 [this is the main issue to finalize Helm's OCI integration], https://github.com/helm/helm/issues/8094, https://github.com/helm/helm/issues/6982, https://github.com/helm/helm/pull/6983, https://github.com/helm/helm/issues/6593, https://github.com/helm/helm/pull/7613, https://github.com/helm/helm/issues/8332, https://github.com/helm/helm/issues/8387, https://github.com/helm/helm/issues/6990), so it seems like the future of this is not certain yet as its already hidden behind an experimental feature flag.

Also here is a similar discussion from sister projects: https://github.com/roboll/helmfile/issues/1403 (has some insights on the topic from same perspective with helmsman), https://github.com/pulumi/pulumi-kubernetes/issues/1314, https://github.com/hashicorp/terraform-provider-helm/issues/396, https://github.com/argoproj/argo-cd/issues/3349, https://github.com/argoproj/argo-cd/pull/4018

ArgoCD seems to be just implemented it like this:
```
  # Add a private Helm OCI-based repository named 'stable' via HTTPS
  argocd repo add helm-oci-registry.cn-zhangjiakou.cr.aliyuncs.com --type helm --name stable --enable-oci --username test --password test
```

Even though we'd really like to use ACR as our helm repo (so that we don't need to maintain an internal helm repo), I think best path here seems to wait for https://github.com/helm/community/pull/136 to reach a conclusion and be followed by the implementation to avoid further migrations or ending up with soon-to-obsolete implementation on helmsman.

**Comment by antoinedeschenes** [comment]
These repos use basic auth? You can specify `https://user:pass@myregistry.com/charts` or setup the repo in helm first with `--user` and `--password` and omit them from the helmRepos section

**Comment by luisdavim** [comment]
I've opened https://github.com/Praqma/helmsman/pull/612 and I'm looking for someone that could test it since I currently don't have access to a setup where I can test it myself...
Also, since https://github.com/Praqma/helmsman/pull/610 Helmsman supports passing a URL for a chart so that could also be an alternative...

**Comment by luisdavim** [comment]
Fixed in https://github.com/Praqma/helmsman/pull/612
More details in https://github.com/Praqma/helmsman/blob/master/docs/how_to/helm_repos/oci.md
